services:
  - type: web
    name: progress-tracker
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"

    envVars:
      - key: TITLE
        value: "進捗管理システム"
      - key: NUMBER_OF_GROUPS
        value: "14"
      - key: TASKS
        value: '["課題1", "課題2", "課題3"]'
      - key: CALL_REASONS
        value: '["質問", "確認", "ヘルプ"]'

      - key: SERVER_HOST
        value: 'http://127.0.0.1'

      - key: SECRET_TOKEN
        generateValue: true
      - key: STUDENT_TOKEN
        generateValue: true
      - key: REMOTE_TOKEN
        generateValue: true